### ISSUE TITLE
kernel don't start, examples code doesn't work online

### ISSUE THREAD

**Issue by maxsagitov** [bioimagebook/bioimagebook.github.io#20]
@petebankhead hello and thanks to share your knowledge!
I have some troubles with dependendences, is it possible to check it?
![ss_BA_fail](https://user-images.githubusercontent.com/17084266/225839600-a9a49f84-4f12-4514-ba9d-6944917cef69.jpg)

**Comment by petebankhead** [comment]
Thanks @maxsagitov I fixed *part* of the issue, but then a new problem emerged that blocks the interactive stuff from working.

The new problem seems to affect more than just this book, so I'm not sure it's something that can be fixed here alone.

I created another GitHub issue about it with Jupyter Book:
* https://github.com/executablebooks/jupyter-book/issues/1978

**Comment by petebankhead** [comment]
I'll close this issue because it should work now.

Since I've just updated the book in the past few minutes, it might be a bit slow to load the first time, but hopefully improves afterwards.

I've also learned that if you turn on live code before you expand the code cells, they don't always expand nicely when you want them to... the `Run` etc. buttons appear, but no code. However clicking inside where the code *should* be (above the buttons) prompts it to appear.
